[versions]
groovyXml = "4.0.23"
spock = "2.4-M4-groovy-4.0"
testcontainersSpock = "1.20.1"
xmlunit = "2.10.0"
cglib = "3.3.0"
mockito = "5.13.0"
logback = "1.5.8"

[libraries]
groovy-xml = { group = "org.apache.groovy", name = "groovy-xml", version.ref = "groovyXml" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
testcointainer-spock = { group = "org.testcontainers", name = "spock", version.ref = "testcontainersSpock" }
xmlunit-core = { group = "org.xmlunit", name = "xmlunit-core", version.ref = "xmlunit" }
cglib = { group = "cglib", name = "cglib", version.ref = "cglib" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }